config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'about' => 'static_pages#about', as: :about

  resource :school
  resource :application, only: [:new, :create, :show, :update] do
    resources :teachers, only: [:new, :create, :edit, :update, :destroy]
    resources :teams, only: [:create, :destroy] do
      resources :students, only: [:new, :create, :edit, :update, :destroy]
    end
    member do
      get 'confirm/:token' => 'applications#confirm', as: :confirm
    end
  end
  get 'signin' => 'sessions#new', as: :new_session
  post 'signin' => 'sessions#create', as: :sessions
  delete 'signout' => 'sessions#destroy', as: :destroy_session

end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :team
	validates :title, presence: true
	validates :fname, presence: true
	validates :lname, presence: true

	def full_name
		"#{title}#{fname} #{lname}"
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :application_required

	def new
		team = current_application.teams.find_by(id: params[:team_id])
		if team.nil?
			flash[:danger] = "ไม่พบทีม"
			redirect_to application_path
		else
			@student = team.students.new
		end
	end

	def create
		team = current_application.teams.find_by(id: params[:team_id])
		if team.nil?
			flash[:danger] = "ไม่พบทีม"
			redirect_to application_path
		else
			@student = team.students.new(student_params)
			if @student.valid?
				@student.save
				app = team.application
				app.revision += 1
				app.save
				redirect_to application_path
			else
				render 'new'
			end
		end
	end

	def edit
		team = Team.find_by(id: params[:team_id])
		if team.nil?
			flash[:danger] = "ไม่พบทีม"
			redirect_to application_path
		else
			@student = team.students.find_by(id: params[:id])
			if @student.nil?
				flash[:danger] = "ไม่พบนักเรียน"
				redirect_to application_path
			end
		end
	end

	def update
		team = Team.find_by(id: params[:team_id])
		if team.nil?
			flash[:danger] = "ไม่พบทีม"
			redirect_to application_path
		else
			@student = team.students.find_by(id: params[:id])
			if @student.nil?
				flash[:danger] = "ไม่พบนักเรียน"
				redirect_to application_path
			else
				@student = @student.update(student_params)
				app = team.application
				app.revision += 1
				app.save
				redirect_to application_path
			end
		end
	end

	def destroy
		team = Team.find_by(id: params[:team_id])
		if team.nil?
			flash[:danger] = "ไม่พบทีม"
			redirect_to application_path
		else
			student = team.students.find_by(id: params[:id])
			if student.nil?
				flash[:danger] = "ไม่พบนักเรียน"
				redirect_to application_path
			else
				student.destroy
				app = team.application
				app.revision += 1
				app.save
				redirect_to application_path
			end
		end
	end

	private
	def student_params
		params.require(:student).permit(:title, :fname, :lname)
	end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<% content_for(:title, 'แก้ไขนักเรียน') %>
<div class="row text-center">
	<h3>แก้ไขนักเรียน</h3>
</div>
<div class="col-md-6 col-md-offset-3">
	<%= form_for(@student, url: application_team_student_path, html: {class: 'form-horizontal'}) do |f| %>
		<%= render 'layouts/errors', models: [@student] %>
		<div class="form-group">
			<%= f.label :title, class: 'col-md-3 control-label' %>
			<div class="col-md-9">
				<%= f.text_field :title, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :fname, class: 'col-md-3 control-label' %>
			<div class="col-md-9">
				<%= f.text_field :fname, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :lname, class: 'col-md-3 control-label' %>
			<div class="col-md-9">
				<%= f.text_field :lname, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group">
			<%= f.submit class: 'btn btn-primary form-control' %>
		</div>
	<% end %>
</div>

app/views/students/new.html.erb
<% content_for(:title, 'เพิ่มนักเรียน') %>
<div class="row text-center">
	<h3>เพิ่มนักเรียน</h3>
</div>
<div class="col-md-6 col-md-offset-3">
	<%= form_for(@student, url: application_team_students_path, html: {class: 'form-horizontal'}) do |f| %>
		<%= render 'layouts/errors', models: [@student] %>
		<div class="form-group">
			<%= f.label :title, class: 'col-md-3 control-label' %>
			<div class="col-md-9">
				<%= f.text_field :title, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :fname, class: 'col-md-3 control-label' %>
			<div class="col-md-9">
				<%= f.text_field :fname, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :lname, class: 'col-md-3 control-label' %>
			<div class="col-md-9">
				<%= f.text_field :lname, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group">
			<%= f.submit class: 'btn btn-primary form-control' %>
		</div>
	<% end %>
</div>