config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'about' => 'static_pages#about', as: :about

  resource :school
  resource :application, only: [:new, :create, :show, :update] do
    resources :teachers, only: [:new, :create, :edit, :update, :destroy]
    resources :teams, only: [:create, :destroy] do
      resources :students, only: [:new, :create, :edit, :update, :destroy]
    end
    member do
      get 'confirm/:token' => 'applications#confirm', as: :confirm
    end
  end
  get 'signin' => 'sessions#new', as: :new_session
  post 'signin' => 'sessions#create', as: :sessions
  delete 'signout' => 'sessions#destroy', as: :destroy_session

end

app/models/application.rb
class Application < ActiveRecord::Base
	belongs_to :school
	belongs_to :subject
	has_many :teams
	has_many :teachers
	has_many :sessions
	validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }, uniqueness: true
	validates :status, presence: true
	has_secure_password
	before_create :generate_token

	STATUS_TEXT = ['ไม่สังกัดโรงเรียน', 'ยังไม่ยืนยันอีเมล', 'ยังไม่ส่งเอกสาร', 'ได้รับเอกสารแล้ว']
	MAX_TEACHERS = 2
	MAX_TEAMS = 2
	def finalise
		errors = []
		addteam = false
		# Check teachers
		if self.teachers.empty?
			errors << :teacher
		end
		# Check teams
		if self.teams.empty?
			errors << :team
		end
		# Check team members
		self.teams.each do |t|
			if t.students.count != 2 and (not addteam)
				errors << t
				addteam = true
			end
		end
		errors
	end

	def status_text
		return STATUS_TEXT[self.status]
	end

	def teacher_addable?
		return self.teachers.count < MAX_TEACHERS
	end

	def team_addable?
		return self.teams.count < MAX_TEAMS
	end

	private
	def generate_token
		self.token = SecureRandom.urlsafe_base64
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
	before_action :application_required, only: [:show]

	def new
		reset_session
		@application = Application.new
		@subjects = Subject.all
		@school = School.new
		@subjects_arr = @subjects.map do |s|
			[s.name, s.id]
		end
	end

	def create
		old_applications = Application.where(email: application_params[:email], status: 0)
		old_applications.destroy_all
		@application = Application.new(application_params)
		@application.status = 0
		@subjects = Subject.all
		@subjects_arr = @subjects.map do |s|
			[s.name, s.id]
		end
		@school = School.new(school_params)
		if school_params[:name].blank?
			@school.errors.add(:name, I18n.t("errors.messages.empty"))
		end
		if (not @application.valid?) or school_params[:name].blank?
			render 'new'
		else
			@school = School.find_by(school_params)
			if @school.nil?
				@application.status = 0
				@application.save
				session[:application_id] = @application.id
				@school = School.new(school_params)
				flash.now[:warning] = "ไม่พบข้อมูลโรงเรียน#{@school.name} กรุณากรอกข้อมูล"
				render 'school_info'
			else
				if @school.applications.find_by(subject: @application.subject).nil?
					@application.save
					session[:application_id] = @application.id
					session[:school_id] = @school.id
					flash.now[:info] = "พบข้อมูลโรงเรียน#{@school.name} กรุณาตรวจสอบข้อมูล"
					render 'application_confirm'
				else
					@application.errors.add(:base, "โรงเรียน#{@school.name} ได้มีการสมัครวิชา#{Subject.find_by(id: application_params[:subject_id]).name}แล้ว")
					render 'new'
				end
			end
		end
	end

	def update # Seriously, this is redirected from the confirmation page.
		@application = Application.find_by(id: session[:application_id])
		@school = School.find_by(id: session[:school_id])
		@application.school = @school
		@application.status = 1
		@application.revision = 1
		@application.save
		reset_session
		Notifications.signup(@application).deliver
		flash[:success] = "ลงทะเบียนเรียบร้อย ระบบได้ทำการส่งอีเมลไปหาท่าน ซึ่งจะมีลิงค์ยืนยัน กรุณาตรวจสอบอีเมลของท่าน"
		redirect_to root_path
	end

	def confirm
		@application = Application.find_by(id: params[:id], token: params[:token])
		if @application.nil?
			flash[:danger] = "เกิดข้อผิดพลาดกับลิงค์ยืนยัน กรุณาลองใหม่ภายหลัง"
		else
			@application.status = 2
			@application.save
			flash[:success] = "ยืนยันการลงทะเบียนเรียบร้อย กรุณาเข้าสู่ระบบ"
		end
		redirect_to root_path
	end

	def show
	end

	private
	def application_params
		params.require(:application).permit(:email, :password, :password_confirmation, :subject_id)
	end

	def school_params
		params.require(:school).permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(title)
		base_title = "การแข่งขันคณิตศาสตร์และวิทยาศาสตร์ระหว่างโรงเรียน ครั้งที่ 13"
		if title.empty?
			base_title
		else
			"#{base_title} | #{title}"
		end
	end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_checklist.html.erb
<% if current_application.finalise.any? %>
	<div class="alert alert-info">
		รายการตรวจสอบ
		<ul>
			<% current_application.finalise.each do |e| %>
				<% case e %>
					<% when :teacher %>
						<li>ไม่มีครูผู้ควบคุม</li>
					<% when :team %>
						<li>ไม่มีทีมนักเรียนเข้าแข่งขัน</li>
					<% else %>
						<li>มีทีมนักเรียนเข้าแข่งขัน ที่มีสมาชิกไม่ครบ 2 คน</li>
					<% end %>
			<% end %>
		</ul>
	</div>
<% else %>
	<div class="text-center">
		<%= link_to 'ดาวน์โหลดใบสมัคร', application_path(format: :pdf) %>
	</div>
	<div class="alert alert-success">
		ใบสมัครเรียบร้อย
	</div>
<% end %>

app/views/applications/application_confirm.html.erb
<% content_for(:title, 'ยืนยันข้อมูล') %>
<h3 class="text-center">ยืนยันข้อมูล</h3>
<div class="col-md-6 col-md-offset-3">
	<%= form_for(@application, html: {class: "form-horizontal"}) do |f| %>
		<div class="form-group">
			<%= f.label :email, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.email_field :email, class: "form-control", readonly: true %>
			</div>
		</div>
		<%= fields_for @application.subject do |s| %>
			<div class="form-group">
				<%= s.label :name, class: "col-md-3 control-label" %>
				<div class="col-md-9">
					<%= s.text_field :name, class: "form-control", readonly: true %>
				</div>
			</div>
		<% end %>
		<%= fields_for @school do |s| %>
			<div class="form-group">
				<%= s.label :name, class: "col-md-3 control-label" %>
				<div class="col-md-9">
					<%= s.text_field :name, class: "form-control", readonly: true %>
				</div>
			</div>
			<div class="form-group">
				<%= s.label :number, class: "col-md-3 control-label" %>
				<div class="col-md-9">
					<%= s.text_field :number, class: "form-control", readonly: true %>
				</div>
			</div>
			<div class="form-group">
				<%= s.label :soi, class: "col-md-3 control-label" %>
				<div class="col-md-9">
					<%= s.text_field :soi, class: "form-control", readonly: true %>
				</div>
			</div>
			<div class="form-group">
				<%= s.label :road, class: "col-md-3 control-label" %>
				<div class="col-md-9">
					<%= s.text_field :road, class: "form-control", readonly: true %>
				</div>
			</div>
			<div class="form-group">
				<%= s.label :subdistrict, class: "col-md-3 control-label" %>
				<div class="col-md-9">
					<%= s.text_field :subdistrict, class: "form-control", readonly: true %>
				</div>
			</div>
			<div class="form-group">
				<%= s.label :district, class: "col-md-3 control-label" %>
				<div class="col-md-9">
					<%= s.text_field :district, class: "form-control", readonly: true %>
				</div>
			</div>
			<div class="form-group">
				<%= s.label :province, class: "col-md-3 control-label" %>
				<div class="col-md-9">
					<%= s.text_field :province, class: "form-control", readonly: true %>
				</div>
			</div>
			<div class="form-group">
				<%= s.label :zip, class: "col-md-3 control-label" %>
				<div class="col-md-9">
					<%= s.text_field :zip, class: "form-control", readonly: true %>
				</div>
			</div>
			<div class="form-group">
				<%= s.label :telephone, class: "col-md-3 control-label" %>
				<div class="col-md-9">
					<%= s.text_field :telephone, class: "form-control", readonly: true %>
				</div>
			</div>
			<div class="form-group">
				<%= s.label :fax, class: "col-md-3 control-label" %>
				<div class="col-md-9">
					<%= s.text_field :fax, class: "form-control", readonly: true %>
				</div>
			</div>
			<div class="form-group">
				<%= s.label :website, class: "col-md-3 control-label" %>
				<div class="col-md-9">
					<%= s.url_field :website, class: "form-control", readonly: true %>
				</div>
			</div>
		<% end %>
		<div class="form-group">
			<%= f.submit class: "btn btn-primary form-control" %>
		</div>
	<% end %>
</div>

app/views/applications/new.html.erb
<% content_for(:title, 'สมัครเข้าร่วมการแข่งขัน') %>
<h3 class="text-center">สมัครเข้าร่วมการแข่งขัน</h3>
<div class="col-md-6 col-md-offset-3">
	<%= render 'layouts/errors', models: [@application, @school] %>
	<%= form_for(@application, url: application_path, html: {class: "form-horizontal"}) do |f| %>
		<div class="form-group">
			<%= f.label :email, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.email_field :email, class: "form-control" %>
			</div>
		</div>
		<%= fields_for(@school) do |s| %>
			<div class="form-group">
				<%= s.label :name, class: "col-md-3 control-label" %>
				<div class="col-md-9">
					<%= s.text_field :name, class: "form-control" %>
				</div>
			</div>
		<% end %>
		<div class="form-group">
			<%= f.label :password, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.password_field :password, class: "form-control" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :password_confirmation, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.password_field :password_confirmation, class: "form-control" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :subject, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.select :subject_id, @subjects_arr, {}, class: "form-control" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.submit class: "btn btn-primary form-control" %>
		</div>
	<% end %>
</div>

app/views/applications/school_info.html.erb
<% content_for(:title, 'ข้อมูลโรงเรียน') %>
<h3 class="text-center">ข้อมูลโรงเรียน</h3>
<div class="col-md-6 col-md-offset-3">
	<%= render 'layouts/errors', models: [@school] %>
	<%= form_for(@school, url: school_path, html: {class: "form-horizontal"}) do |f| %>
		<div class="form-group">
			<%= f.label :name, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.text_field :name, class: "form-control", readonly: true %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :number, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.text_field :number, class: "form-control" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :soi, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.text_field :soi, class: "form-control" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :road, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.text_field :road, class: "form-control" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :subdistrict, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.text_field :subdistrict, class: "form-control" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :district, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.text_field :district, class: "form-control" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :province, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.text_field :province, class: "form-control" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :zip, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.text_field :zip, class: "form-control" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :telephone, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.text_field :telephone, class: "form-control" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :fax, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.text_field :fax, class: "form-control" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.label :website, class: "col-md-3 control-label" %>
			<div class="col-md-9">
				<%= f.text_field :website, class: "form-control" %>
			</div>
		</div>
		<div class="form-group">
			<%= f.submit class: "btn btn-primary form-control" %>
		</div>
	<% end %>
</div>

app/views/applications/show.html.erb
<% content_for(:title, 'แก้ไขใบสมัคร') %>
<div class="row text-center">
	<div class="text-right">
		ฉบับแก้ไขครั้งที่ <%= current_application.revision %><br/>
		แก้ไขล่าสุดเมื่อ <%= current_application.updated_at %>
	</div>
	<h3>แก้ไขใบสมัคร</h3>
	<h5>โรงเรียน<%= current_application.school.name %><br/>
	<%= current_application.school.full_address %><br/>
	<%= current_application.school.contact_information %><br/>
	<% if not current_application.school.website.blank? %>
		<%= link_to current_application.school.website %><br/>
	<% end %>
	สาขาวิชา<%= current_application.subject.name %><br/>
	<b>สถานะ : <%= current_application.status_text %></b></h5>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<%= render 'checklist' %>
	</div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div>
			<span class="h4">รายชื่อครูผู้ควบคุม</span>
			<% if current_application.teacher_addable? %>
				<%= link_to '[เพิ่มครู]', new_application_teacher_path %>
			<% end %>
		</div>
		<% if current_application.teachers.any? %>
			<table class="table table-condensed table-responsive">
				<tr>
					<th>
						ชื่อ-สกุล
					</th>
					<th>
						[ลบ]
					</th>
					<th>
						[แก้ไข]
					</th>
				<tr>
				<% current_application.teachers.each do |t| %>
					<tr>
						<td>
							<%= t.full_name %>
						</td>
						<td>
							<%= link_to '[ลบ]', application_teacher_path(t), method: :delete %>
						</td>
						<td>
							<%= link_to '[แก้ไข]', edit_application_teacher_path(t) %>
						</td>
					</tr>
				<% end %>
			</table>
		<% else %>
			ไม่มีครูผู้ควบคุมทีม
		<% end %>
	</div>
</div>
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div>
			<span class="h4">รายชื่อทีมนักเรียนเข้าแข่งขัน</span>
			<% if current_application.team_addable? %>
				<%= link_to '[เพิ่มทีม]', application_teams_path, method: :post %>
			<% end %>
		</div>
		<% if current_application.teams.any? %>
			<table class="table table-condensed table-responsive">
				<tr>
					<th>
						ทีม
					</th>
					<th>
						การดำเนินการ
					</th>
				</tr>
				<% i = 1 %>
				<% current_application.teams.each do |t| %>
					<tr>
						<td>
							<div>
								ทีมที่ <%= i %>
							</div>
							<% if t.students.any? %>
								<% t.students.each do |s| %>
									<div>
										<%= s.full_name %> <%= link_to '[แก้ไข]', edit_application_team_student_path(t, s) %> <%= link_to '[ลบ]', application_team_student_path(t, s), method: :delete %>
									</div>
								<% end %>
							<% else %>
								<div>
									ไม่มีนักเรียน
								</div>
							<% end %>
						</td>
						<td>
							<% if t.student_addable? %>
								<%= link_to '[เพิ่มนักเรียน]', new_application_team_student_path(t) %>
							<% end %>
							<%= link_to '[ลบทีม]', application_team_path(t), method: :delete %>
						</td>
					</tr>
					<% i += 1 %>
				<% end %>
			</table>
		<% else %>
			ไม่มีทีมนักเรียนเข้าแข่งขัน
		<% end %>
	</div>
</div>