config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'about' => 'static_pages#about', as: :about

  resource :school
  resource :application, only: [:new, :create, :show, :update] do
    resources :teachers, only: [:new, :create, :edit, :update, :destroy]
    resources :teams, only: [:create, :destroy] do
      resources :students, only: [:new, :create, :edit, :update, :destroy]
    end
    member do
      get 'confirm/:token' => 'applications#confirm', as: :confirm
    end
  end
  get 'signin' => 'sessions#new', as: :new_session
  post 'signin' => 'sessions#create', as: :sessions
  delete 'signout' => 'sessions#destroy', as: :destroy_session

end

app/views/notifications/aaa.text.erb
ยินดีต้อนรับเข้าสู่การแข่งขันคณิตศาสตร์และวิทยาศาสตร์ระหว่างโรงเรียน ครั้งที่ 13 ประจำปีการศึกษา 2557

เรื่อง การยืนยันการลงทะเบียน
เรียน คุณครู/ผู้สมัคร โรงเรียน<%= @application.school.name %>

เพื่อให้การลงทะเบียนเสร็จสมบูรณ์ กรุณาคลิกที่ลิงค์ดังต่อไปนี้

TODO

ด้วยความเคารพ
คณะกรรมการจัดการแข่งขันคณิตศาสตร์และวิทยาศาสตร์ระหว่างโรงเรียน ครั้งที่ 13 ประจำปีการศึกษา 2557
งานกิจกรรมพัฒนาผู้เรียน
โรงเรียนเตรียมอุดมศึกษา

# Application ID <%= @application.id %>
# Subject ID <%= @application.subject.id %>
# Creation Time <%= @application.created_at %>

app/views/notifications/signup.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
	</head>
	<body style="font-family: arial, helvetica, sans-serif;font-size: 13px;">
		<span style="font-size: 16px;">ยินดีต้อนรับเข้าสู่การแข่งขันคณิตศาสตร์และวิทยาศาสตร์ระหว่างโรงเรียน ครั้งที่ 13 ประจำปีการศึกษา 2557</span><br/>
		<br/>
		เรื่อง การยืนยันการลงทะเบียน<br/>
		เรียน คุณครู/ผู้สมัคร โรงเรียน<%= @application.school.name %><br/>
		<br/>
		เพื่อให้การลงทะเบียนเสร็จสมบูรณ์ กรุณาคลิกที่ลิงค์ดังต่อไปนี้<br/>
		<br/>
		<%= link_to confirm_application_url(@application, @application.token), confirm_application_url(@application, @application.token) %><br/>
		<br/>
		ด้วยความเคารพ<br/>
		คณะกรรมการจัดการแข่งขันคณิตศาสตร์และวิทยาศาสตร์ระหว่างโรงเรียน ครั้งที่ 13 ประจำปีการศึกษา 2557<br/>
		งานกิจกรรมพัฒนาผู้เรียน<br/>
		โรงเรียนเตรียมอุดมศึกษา<br/>
		<br/>
		<span style="font-family: courier new, monospace;">
			# Application Number <%= @application.id %><br/>
			# Subject ID <%= @application.subject.id %><br/>
			# Creation Time <%= @application.created_at %><br/>
		</span>
	</body>
</html>