config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'about' => 'static_pages#about', as: :about

  resource :school
  resource :application, only: [:new, :create, :show, :update] do
    resources :teachers, only: [:new, :create, :edit, :update, :destroy]
    resources :teams, only: [:create, :destroy] do
      resources :students, only: [:new, :create, :edit, :update, :destroy]
    end
    member do
      get 'confirm/:token' => 'applications#confirm', as: :confirm
    end
  end
  get 'signin' => 'sessions#new', as: :new_session
  post 'signin' => 'sessions#create', as: :sessions
  delete 'signout' => 'sessions#destroy', as: :destroy_session

end

app/views/layouts/_errors.html.erb
<% err_count = 0 %>
<% models.each do |m| %>
	<% err_count += m.errors.count %>
<% end %>
<% if err_count > 0 %>
	<div class="alert alert-danger">
		มีข้อผิดพลาด <%= err_count %> จุด ดังต่อไปนี้
		<ul>
			<% models.each do |m| %>
				<% m.errors.full_messages.each do |e| %>
					<li><%= e %></li>
				<% end %>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	</head>
	<body>
		<div class="navbar navbar-default navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<%= link_to 'TUMSO 13th', root_path, class: "navbar-brand" %>
				</div>
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li><%= link_to 'หน้าแรก', root_path %></li>
						<li><%= link_to 'เกี่ยวกับ', about_path %></li>
						<% if current_application %>
							<li><%= link_to 'แก้ไขใบสมัคร', application_path %></li>
						<% end %>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<% if current_application.nil? %>
							<li><%= link_to 'เข้าสู่ระบบ', new_session_path %></li>
						<% else %>
							<li><%= link_to 'ออกจากระบบ', destroy_session_path, method: :delete %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
		<div class="main_body container">
			<% flash.each do |k, v| %>
				<div class="alert alert-<%= k %>"><%= v %></div>
			<% end %>
			<%= yield %>
		</div>
		<% if Rails.env.development? %>
			<%= debug(params) %>
		<% end %>
	</body>
</html>